// This file is autogenerated by Mint from your localized strings file.

import Foundation

private class BundleLocator {
    static let bundle: Bundle = Bundle(for: BundleLocator.self)
}

struct Mint {

    struct common {
        static let have_question = NSLocalizedString("common.have_question", bundle: BundleLocator.bundle, comment: "")
        static let ok = NSLocalizedString("common.ok", bundle: BundleLocator.bundle, comment: "")
    }

    struct common {
        static let have_question = NSLocalizedString("common.have_question", bundle: BundleLocator.bundle, comment: "")
        static let ok = NSLocalizedString("common.ok", bundle: BundleLocator.bundle, comment: "")
    }

    struct common {
        static let register_title = NSLocalizedString("common.register_title", bundle: BundleLocator.bundle, comment: "")
        static let register_title_too_long_text = NSLocalizedString("common.register_title_too_long_text", bundle: BundleLocator.bundle, comment: "")
    }

    struct common {
        static let register_title = NSLocalizedString("common.register_title", bundle: BundleLocator.bundle, comment: "")
        static let register_title_too_long_text = NSLocalizedString("common.register_title_too_long_text", bundle: BundleLocator.bundle, comment: "")
    }

}
