//
// Autogenerated by Mint
// Do not change this file manually!
//

import Foundation

// MARK: - Localizations
public struct Localizations {

	// MARK: - Common Keys
	public struct Common {

		/// Base translation: Ok
		public static var Ok: String = NSLocalizedString("common_ok", comment: "")

		/// Base translation: Do you have a question?
		public static var HaveQuestion: String = NSLocalizedString("common_have_question", comment: "")

		/// Base translation: fields must be at between {min} - {max} characters
		public static func ErrorEmptyField(min: String, max: String) -> String {
			var keyValue = NSLocalizedString("common_error_empty_field", comment: "")
			keyValue = keyValue.replacingOccurrences(of: "{min}", with: min)
			keyValue = keyValue.replacingOccurrences(of: "{max}", with: max)
			return keyValue
		}

	}

	// MARK: - Home Keys
	public struct Home {

		/// Base translation: Home
		public static var Title: String = NSLocalizedString("home_screen_title", comment: "")

	}

	// MARK: - Login Keys
	public struct Login {

		/// Base translation: Register Title
		public static var RegisterTitle: String = NSLocalizedString("login_screen_register_title", comment: "")

		/// Base translation: Register Long Text
		public static var RegisterTitleTooLongText: String = NSLocalizedString("login_screen_register_title_too_long_text", comment: "")

		/// Base translation: {field} is required.
		public static func RegisterFieldRequired(field: String) -> String {
			var keyValue = NSLocalizedString("login_screen_register_field_required", comment: "")
			keyValue = keyValue.replacingOccurrences(of: "{field}", with: field)
			return keyValue
		}

		/// Base translation: {field} should be at least {min} character.
		public static func RegisterFieldMin(field: String, min: String) -> String {
			var keyValue = NSLocalizedString("login_screen_register_field_min", comment: "")
			keyValue = keyValue.replacingOccurrences(of: "{field}", with: field)
			keyValue = keyValue.replacingOccurrences(of: "{min}", with: min)
			return keyValue
		}

	}

	// MARK: - Profile Keys
	public struct Profile {

		/// Base translation: Profile
		public static var Title: String = NSLocalizedString("profile_screen_title", comment: "")

	}

	// MARK: - Register Keys
	public struct Register {

		/// Base translation: Register
		public static var Title: String = NSLocalizedString("register_screen_title", comment: "")

	}

	// MARK: - UserDetail Keys
	public struct UserDetail {

		/// Base translation: User Detail
		public static var Title: String = NSLocalizedString("user_detail_screen_title", comment: "")

	}

}
