//
// This file is autogenerated by Mint from your localized strings file.
//

import Foundation

struct Mint {

    struct common {

        /// Ok
        static let ok = NSLocalizedString("common.ok", bundle: Bundle.main, comment: "")

        /// Do you have a question?
        static let have_question = NSLocalizedString("common.have_question", bundle: Bundle.main, comment: "")

    }

    struct common {

        /// Ok
        static let ok = NSLocalizedString("common.ok", bundle: Bundle.main, comment: "")

        /// Do you have a question?
        static let have_question = NSLocalizedString("common.have_question", bundle: Bundle.main, comment: "")

    }

    struct common {

        /// Register Title
        static let register_title = NSLocalizedString("common.register_title", bundle: Bundle.main, comment: "")

        /// Register Long Text
        static let register_title_too_long_text = NSLocalizedString("common.register_title_too_long_text", bundle: Bundle.main, comment: "")

    }

    struct common {

        /// Register Title
        static let register_title = NSLocalizedString("common.register_title", bundle: Bundle.main, comment: "")

        /// Register Long Text
        static let register_title_too_long_text = NSLocalizedString("common.register_title_too_long_text", bundle: Bundle.main, comment: "")

    }

}
