//
// Autogenerated by Mint
// Do not change this file manually!
//

import Foundation

// MARK: - Localizations
public struct Localizations {

	// MARK: - A Keys
	public struct A {

		/// Base translation: A ViewController
		public static var Title: String = NSLocalizedString("a_screen_title", comment: "")

	}

	// MARK: - B Keys
	public struct B {

		/// Base translation: B ViewController
		public static var Title: String = NSLocalizedString("b_screen_title", comment: "")

	}

	// MARK: - Home Keys
	public struct Home {

		/// Base translation: Home
		public static var Title: String = NSLocalizedString("home_screen_title", comment: "")

	}

}
