//
// Autogenerated by Mint
// Do not change this file manually!
//

import Foundation

// MARK: - Localizations
public struct Localizations {

	// MARK: - A Keys
	public struct A {

		/// Base translation: A ViewController
		public static var Title: String = NSLocalizedString("a_screen_title", comment: "")

	}

	// MARK: - B Keys
	public struct B {

		/// Base translation: Register \"Title %s5
		public static var Title: String = NSLocalizedString("b_screen_title", comment: "")

		/// Base translation: fields must be at between {min} - {max} characters
		public static func ErrorEmptyField(min: String, max: String) -> String {
			var keyValue = NSLocalizedString("b_screen_error_empty_field", comment: "")
			keyValue = keyValue.replacingOccurrences(of: "{min}", with: min)
			keyValue = keyValue.replacingOccurrences(of: "{max}", with: max)
			return keyValue
		}

	}

	// MARK: - Home Keys
	public struct Home {

		/// Base translation: Home
		public static var Title: String = NSLocalizedString("home_screen_title", comment: "")

	}

}
