//
//  Generator.swift
//  Mint
//
//  Created by Mustafa GUNES on 6.02.2020.
//  Copyright © 2020 Mustafa GUNES. All rights reserved.
//

import Foundation

public struct Generator {
    
    public static func generate(keyValues: [String: [String: String]]) -> String {
        var swift = "//\n"
        swift += "// This file is autogenerated by Mint from your localized strings file.\n"
        swift += "//\n\n"
        swift += "import Foundation\n\n"
        swift += "struct Mint {\n\n"
//        for (index, value) in keyValues.enumerated() {
//            for key in keyValues {
//                swift += swiftFor(struct: keyValues.keys.first ?? "nil bu", keyValues: key.value)
//                swift += "\n\n"
//            }
//            if index < keyValues.count - 1 {
//                swift += "\n"
//            }
//        }
        for key in keyValues {
            for mappedArr in key.value {
                swift += generateStructAndKeys(structName: keyValues.keys.first ?? "nil", keyValues: key.value)
                swift += "\n\n"
            }
        }
        swift += "}\n"
        return swift
    }
    
    private static func generateStructAndKeys(structName: String, keyValues: [String: String]) -> String {
        var swift = "    struct \(structName) {\n"
        for key in keyValues {
            let lowercasedKey = key.key.lowercaseFirstCharacter()
            let nsLocalizedKey = "\(structName).\(key.key)"
            swift += "\n        /// \(key.value)"
            swift += "\n        static let \(lowercasedKey) = NSLocalizedString(\"\(nsLocalizedKey)\", bundle: Bundle.main, comment: \"\")\n"
        }
        swift += "\n    }"
        return swift
    }
}
